### ISSUE TITLE
Use of Telemetry in Zowe Explorer (and collecting info in general)

### ISSUE THREAD

**Issue by zdmullen** [zowe/community#959] opened 2020-12-09 14:53 UTC
This stems from the discussion that I brought up in the December 9 meeting. 

The question is about introducing telemetry in Zowe Explorer. As a Visual Studio Code extension, we can follow the guidance that VS Code provides for implementing telemetry in extensions to do so in Zowe Explorer. This of course raises several questions for the dev team and others to resolve:

- What is the scope for the information we want to collect? UI or specific data, a mix of both? 
- How do we set up an Azure account where the data can be collected *and* accessed by squad members?
- What is the best way to bring this to the attention of users and what is the default behavior?

From this initial question, we also talked about collection of user data in z/OS and also the API ML (both of which were discussed at some point in the past). 

Shall we have a more formal discussion of this in a future ZLC meeting? Who should the team follow up with otherwise? 

Thanks!

**Comment by armstro** [comment] 2021-01-19 21:19
Sorry - duplicate of issue 953 - closing this one

**Closed by armstro** 2021-01-19 21:19 UTC
