### ISSUE TITLE
Retrospective on release issues as-is

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#915] opened 2020-12-18 09:43 UTC
**Is your feature request related to a problem or limitation? Please describe.**
Zowe releases historically have not met their schedule release date for a number of issues.
This has been for a number of issues:
- Infrastructure problems with components of the pipeline (marist, jenkins, docker swarm, ...)
- Defects found in manual testing not picked up earlier
- Release of components into staging that break builds where PR tests have not been performed prior to merge
- other, ...

**Describe the experience you'd like**
Release dates met with more accuracy and consistency

**Suggested solution**
Analyze why releases haven't met their dates collecting information from CICD and present this to the TSC.
This issue to track creating the retrospective to help guide the way forward and be a fact gathering, information sharing exercise.

**Comment by balhar-jakub** [comment] 2021-01-07 20:07
Based on the meeting of 20210107 we need to take a look also at the visibility of when will the releases be and who is involved in the release process. We need to make sure that this is simple to find for anyone looking for it.

**Comment by jackjia-ibm** [comment] 2021-01-07 21:49
For visibility of who are involved in the release process, here are the steps we usually do for a release with my understanding:

_Zowe manifest mentioned below means the `manifest.json` file located in the root folder of https://github.com/zowe/zowe-install-packaging repository._

- Prepare and verify RC
  * Confirm with squads what they want to put into the coming release.
    - Input: PRs from squads against `rc` branch on Zowe manifest `binaryDependencies`
    - Output: Finalized Zowe manifest `binaryDependencies` on `rc` branch.
    - People involved: System Squad and all other squads lead or CI/CD focal point.
  * Build, verify and announce RC
    - Input: `rc` branch build of `zowe-install-packaging` pipeline and test result.
    - Output: RC build announced to community.
    - People involved: System Squad.
  * Verify RC from community and collect feedbacks
    - Input: RC build
    - Output: Verification result.
    - People involved: System Squad and all other squads key committers.
   * Prepare release documentation
     - Input: All inputs from other squads related to the coming release, PRs from squads and updated CHANGELOG.
     - Output: Content in https://github.com/zowe/docs-site `docs-staging` branch are up to speed.
     - People involved: Docs Squad and all squads involved in the coming release.
- Promote RC as formal release
  * Vote RC for release
    - Input: RC build
    - Output: Confirmation based on vote result
    - People involved: System Squad, ZLC in the past, TSC in the future
  * Finalize Zowe manifest `sourceDependencies`, all versions should be static.
    - Input: RC build Zowe manifest `binaryDependencies`.
    - Output: Zowe manifest `sourceDependencies`.
    - People involved: System Squad.
  * Update BOM and run license scan
    - Input: Zowe manifest `sourceDependencies`
    - Output: BOM updates on docs-site docs-staging branch, license Artifact and updated license version in Zowe manifest `binaryDependencies`.
    - People involved: System Squad, Docs Squad.
  * Build, verify final release
    - Input: https://github.com/zowe/zowe-install-packaging `rc` branch
    - Output: https://github.com/zowe/zowe-install-packaging `master` branch, verified Zowe build from master branch.
    - People involved: System Squad.
  * Finalize docs.zowe.org update
    - Input: Content updates on https://github.com/zowe/docs-site `docs-staging` branch.
    - Output: Approved PR (`docs-staging` => `master`) on https://github.com/zowe/docs-site
    - People involved: Docs Squad and other stake holders.
  * Prepare zowe.org update
    - Input: artifacts information of coming release, including artifacts changes and SMP/E PTF numbers.
    - Output: Approved PR on https://github.com/zowe/zowe.github.io
    - People involved: System Squad, Docs Squad and other stake holders including OMP.
- Collaborations on final release
  * Promote final release with zowe-promote-publish pipeline.
    - Input: Zowe build from master branch.
    - Output: Zowe final release, which including artifacts of convenience build, SMP/E build, docker images and source tarball. Also it including hashes of all binaries and signatures.
    - People involved: System Squad.
  * Update docs.zowe.org
    - Input: https://github.com/zowe/docs-site PR (`docs-staging` => `master`) and approval from stake holders
    - Output: Updated docs.zowe.org
    - People involved: Docs Squad and other stake holders who helped on verifying the changes.
  * Update zowe.org
    - Input: https://github.com/zowe/zowe.github.io PR and approval from stake holders
    - Output: Updated zowe.org, especially announcement and download section.
    - People involved: System Squad, Docs Squad.
  * Send Upload Term to OMP
    - Input: Release information including version, all artifacts, signed results and artifact hashes.
    - Output: OMP confirmation and follow up promotions to community.
    - People involved: System Squad, OMP stake holder(s).

**Comment by jackjia-ibm** [comment] 2021-01-07 23:45
Issues on release I'm aware of. @stevenhorsman please feel free to comment if I miss anything, or if any of them are not accurate.

We can compare between RCs and final release to understand what caused to build a new RC. Please let me know if we want to do that. In my memory, new RCs are caused by bugs we found in RC release. But with v1.17.0 and v1.18.0, we also significantly affected by build and test environment failures which had slowed down release process. But before v1.17.0, I don't remember build/test environment has impact on release, but please correct me.

1. Jenkins
  * We used to have connection timeout issues in the past, but it happened in short period of time and didn't last long. But in the past few months, this issue became significant and we cannot even get a reliable nightly build.
    - Severity: this became critical to us. We used to have 50% chance to fail.
    - Mitigation: we setup another Jenkins agent on a new data center, which seems greatly reduced the network connection issue. Based on Steve's estimation, the failure rate was dropped from 50% to 5%.
    - Possible solution(s):
      * Setup another Jenkins agent and see if we can avoid this issue.
      * Suggested to research on Jenkins alternatives, will be a 21PI1 item.
  * If we have many concurrent jobs kicked off, the docker daemon may have a chance to stop reacting because the build jobs will compete the resources usage on Jenkins servers. Sometimes this will recover by itself, but sometimes we may need to intervene and restart Docker daemon.
    - Possible solution(s):
      * None for now except to manually fix the failure.
  * Jenkins master has not been upgraded for a long time. One big reason is we are heavily depend on Jenkins pipeline, which are represented as several core Jenkins pipeline plugins. We found pipeline failures after upgrade which blocked us  from upgrade easily.
    - Possible solution(s):
      * Upgrade our pipelines and shared library and make it compatible with latest version of Jenkins pipeline plugins.
      * Migrate away from Jenkins Pipeline.
  * Current Jenkins is hosted by IBM. It's better to move to "open infrastructure" which hosted by 3rd party.
    - Possible solution(s):
      * Suggested to research on Jenkins alternatives, will be a 21PI1 item.
2. Marist Systems
  * Account on ACF2/TSS systems constantly been locked out. This could be triggered by password expiration and invalid passwords were sent to the systems. Roy tried to reset the SUSPEND rule on the account but wasn't very successful and caused other issues.
    - Possible solutions:
      * Remove SUSPEND rules.
      * Remove account password expiration, especially on Zowe runtime users.
  * Permission/configuration changes required to be applied on the systems. This is either because of new feature added, or we have incorrect setup before.
    - Issues:
      * For RACF system, we work with Marist directly and it usually been resolved fast. But with the changes, Marist side may feel it's becoming overwhelming to catch up.
      * Changes related to ACF2/TSS systems, we rely on Broadcom experts and may take longer time to resolve.
    - Possible solution(s):
      * Request higher level admin permission on the systems so we can apply changes ourselves.
      * Find and add more ACF2/TSS experts to the team.
  * Build failures related to volumes usage.
    - Issues:
      * Volumes on Marist systems are not designed well. There are no effective storage class defined, and the default work volume space are very limited. We constantly hit out of space issue.
      * Work volume changes with `VATLSTxx` are not working well on the servers. We cannot find a proper solution for this. As consequences, we cannot change the default work volumes. We do have a 25G volume defined in `VATLSTxx` but it doesn't take effect (maybe used as temporary data set space).
      * Our build/test pipeline will write logs or create temporary files to user home directory or `/tmp` directory and fall out of the scope of current cleanup procedures. Those 2 volumes are very small.
      * Failed builds may leave some temporary data sets and it will accumulate and eat free space if it's not freed up. We have code to clean up after a failed build, but there are still chances the data sets will be left there because when the cleanup happens, some jobs creating the data sets are still running. 
    - Incidents:
      * There are several times nightly build hit this issue and we have to login to server and cleanup, either data sets or USS files.
      * Zowe Launcher requires `xlclang` compiler, which misses a data set on the system. When trying to resolve the issue, we noticed `VATLSTxx` didn't work on the system, so created Storage Class, but it has conflicts with our mitigations of volume usage and we found we cannot configure `VATLSTxx` to increase temporary data set space. We reverted the changes on volumes and later on Marist side found and installed the missing data set of `xlclang` compiler.
    - Possible solutions:
      * Many usage of volume in our build/test process, we have chance to specify which volume to use. But there are still many cases the data will be put into default work volumes. That's potential risks.
      * We should point all possible USS temporary files to `/ZOWE/tmp` instead of assuming and putting into `/tmp`.
      * We should improve build cleanup process to cancel running jobs kicked of by the build and clean up all possible data sets created.
      * Find potential issues and properly define `VATLSTxx` to make the big volume take effect.
  * Server failures potentially caused by performance test.
    - Issue:
      * After 2 successful run of performance test, the 3rd run may cause a system failure. After investigation, it could related to the JES2 `BERTNUM` parameter. This is completely new to us and we don't have experience.
      * The server has relatively small `BERTNUM` parameter and small JES spool data set (80 tracks).
    - Possible solutions:
      * Recover from backup, which is what we did for that incident.
      * Estimate number of jobs we may create during a day before daily cleanup, calculate and reconfigure the system with proper `BERTNUM` and JES spool data set size. To properly estimate, we need to gain knowledge of what API endpoints will create a job behind the scene and may potential cause the spool to be filled up.
      * Acquire a new "dedicated" performance test server to reduce the risk of affecting build/test.
3. Other challenges
  * Increasingly complicated installation test scenarios we want to cover. Many test scenarios are pre-reqs to announce RC or formal release, and this will slow down the RC/formal release automated verification.
    - Issues:
      * We will grow with more installation test scenarios we want to cover.
      * All installation tests are NOT running in parallel for now.
    - Possible solutions:
      * Automated provisioning new z/OS systems so we can run all tests in parallel.
      * Improve installation test to allow running tests on RACF/ACF2/TSS systems in parallel.
  * Increasingly complicated cross squads efforts which means squad level component testing is not enough. We need more collaborations on Zowe level integration tests.
    - Issues:
      * Zowe build smoke test doesn't cover new features we want to release.
    - Possible solutions:
      * Add more test cases to cover cross-squad features.

Few chances we have issues on Artifactory, but so far I don't see it affects any release with our mitigations. Please let me know if you want to know more about this.

**Comment by stevenhorsman** [comment] 2021-01-08 12:10
@jackjia-ibm - My RC and release process is doc'd in https://github.com/zowe/zowe-install-packaging/issues/1883 and https://github.com/zowe/zowe-install-packaging/issues/1882, but I think it's broadly similar, just some of the details and formatting differ.

I think your issues list is good. Unfortunately with the lack of slack history doing a diagnosis on the RC delays is going to be tricky, and the pipeline issues with Marist have lasted so long that most of previous problems have gone, but I think it can be summarised by lack of test coverage in scenarios, lack of component changes being tested at a zowe-install-test fully integrated level before they are released/pushed to staging, and/or code being rushed in before (or often after) the code freeze deadline that hasn't been validated in builds.

There have also been issues that's aren't with infrastructure, that I'd put down to communication. Lots of instances that squads miss dates for code freeze, or don't give feedback on test results for a week, which is incompatible which makese getting a release done in 4 days impossible.

I think a great first step would be for a release body, with reps from all squads (which might be the TSC) to have regular, short scrums during the release process (including shortly before code-freeze), so that everyone is clear of the status and we don't lose time due to people missing slack messages. This same body should do a retrospective/RCA of any delays after each release and create actions for things that can be improved in the next release.

**Comment by balhar-jakub** [comment] 2021-01-11 10:49
Just note for distant future. 

I would really like to be able to release the Zowe with a click of a button. Just one click that would build all components, run the full test suites for all components and for the Zowe as the whole. Package everything properly and if this whole process succeeds, it will promote the packaged Zowe as a new version together with publishing the new docs. 

Basically removing all the manual steps. The click of the button could be done in such way that it would require approval by multiple people to do the click so we minimize the risk of misuse.

**Comment by balhar-jakub** [comment] 2021-01-29 12:51
As for the coordination, I try starting a discussion around the coordination meeting in zowe-tsc channel. 

Regardless of which time schema we select I propose that for the duration of the testing starting from the day of RC Build a small group will meet daily to coordinate on the release until we get it out of doors.

This group needs to have one representative from Web UI squad, Systems Squad and API ML squad based on the discussions from yesterday.

- @Jakub Balhar I am willing to represent API ML squad.
- Looking for representatives from Systems Squad (@Jack T. Jia, @Tom Zhang can you find someone?)
- Looking for representative from  Web UI squad(@Irek, @Sean Grady can you find someone?)

As for the time. Would 3 PM EST for 15 minutes work?

I would like to try for the next release at least and then we will see, whether it works.

**Comment by jackjia-ibm** [comment] 2021-02-01 20:18
I recorded most of the conversations regarding v1.19.0 release and here is the doc: [release-retrospective-1.19.0.pptx](https://github.com/zowe/community/files/5906516/release-retrospective-1.19.0.pptx). We can discuss details about what are the issues and how should we improve.

**Comment by Joe-Winchester** [comment] 2021-02-12 10:50
Hi @jackjia-ibm - this is great.  I've put some of the key dates into a google calendar as it's a good way to visualize a timeline and also added this to the deck in chart 2.  
[release-retrospective-1.19.0 with google calendar.pptx](https://github.com/zowe/community/files/5971180/release-retrospective-1.19.0.with.google.calendar.pptx)

For the rc2 dates, on slide 1 is has Jan 25 and slide 5 has it as Jan 22nd.  Are these meant to be different events for RC2 of is one incorrect ?
On slide 1 you have the GA date of Jan 29th and the timeline chart 7 shows the upload send to OMP of Feb 1st.  Is Jan 29th GM (i.e. golden master) and Feb 1st GA (i.e. general availability) ?



![image](https://user-images.githubusercontent.com/28100302/107758844-5d337800-6d1f-11eb-909f-5bb6882d601b.png)

**Comment by jackjia-ibm** [comment] 2021-02-12 14:23
Thanks @Joe-Winchester good catch. The GA date on slide 1 should be Feb 1. The slide was created during the time, I was expecting to release at Jan 29. RC2 is on Jan 25 which is correct. Jan 22 was the date APIML released the fix.

The Google calendar view looks great, very clear. Thanks!

**Comment by balhar-jakub** [comment] 2021-02-16 15:30
This is a somewhat related issue: #520

**Comment by jackjia-ibm** [comment] 2021-02-24 21:43
Improvements we discussed during Feb 16 architecture call:

* Related to release process,
  - Vote stop ship in TSC Slack channel other than Thursday meeting to achieve faster response time.
  - Run daily standup after RC1 is announced until RC passes TSC voting.
* Related to automated test to help identifying issues earlier,
  - [Add more automation around docker image](https://github.com/zowe/zowe-install-packaging/issues/1891) - closed
  - [Run full test suite between releases](https://github.com/zowe/zowe-install-packaging/issues/1752) - closed
  - [Enhancement: Support pipline.systemTest() with rules for PRs](https://github.com/zowe/zowe-install-packaging/issues/685) to automatically kick off test after build - in progress as of Feb 24
  - [Report pull request test result as github comment](https://github.com/zowe/zowe-install-packaging/issues/1937)
* Related to release/promote pipeline,
  - [Change zlux to release before building Zowe RC](https://github.com/zowe/zlux/issues/623)
  - [Automated License Notices](https://github.com/zowe/zowe-install-packaging/issues/1052)
  - [Automated Zowe license update](https://github.com/zowe/zowe-install-packaging/issues/1053)
  - [Enhancement: License Scan opens PR on docs-site](https://github.com/zowe/zowe-install-packaging/issues/716)

Potential actions may help:
* Increase code coverage based on SonarCloud scanning result
* Add test cases in relevant level (zowe integration or component level) to test against stop ships we identified.

**Comment by FlappiTomic** [comment] 2021-03-29 22:14
[release-retrospective-1.20.0.pptx](https://github.com/zowe/community/files/6224848/release-retrospective-1.20.0.pptx)

**Comment by balhar-jakub** [comment] 2021-04-15 17:57
I propose we close this issue. The retrospective for each release is already part of the standard process.

**Closed** 2021-04-30 06:54 UTC
Labels: 21PI1, TSC, enhancement
