### ISSUE TITLE
Update the Zowe.Org ACTIVE-MAINTENANCE Release Timeline

### ISSUE THREAD

**Issue by RASakach** [zowe/community#2263] opened 2024-07-08 21:28 UTC
The current ACTIVE - MAINTENANCE release timeline does not reflect the anticipate V3 LTS release.   

This request is to revise the visual to reflect the revised v3 schedule, include the anticipated maintenance schedule and the anticipated v4.x release.  We should also mention "LTS" where appropriate.

The current visual is posted here:  https://www.zowe.org/download

**Comment by balhar-jakub** [comment] 2024-07-09 07:35
The updated chart is in this PR - https://github.com/zowe/zowe.github.io/pull/931

**Comment by balhar-jakub** [comment] 2024-07-09 07:37
![Screenshot 2024-07-09 at 9 36 49](https://github.com/zowe/community/assets/1757251/b3cd20d1-61e0-408d-a992-b9eaa8b495e2)

**Comment by RASakach** [comment] 2024-07-09 14:43
Thanks @balhar-jakub Jakub - 2 more changes to consider please:
(1) The v2.x maintenance line should terminate ~  end of Q3 2026, correct?  If you agree, can you adjust that gray line?
(2)  On the left side of the chart where the Zowe releases are named, can we add LTS to the entries?  i.e. Zowe v1.x LTS, Zowe v2.x LTS etc.?  We mention LTS in the verbiage below but do not identify it anywhere.

**Comment by balhar-jakub** [comment] 2024-07-11 10:54
1) The v2.x terminates 2 and a half year after the release. This means that it should terminal End of March 2027, unless I missed some changes in the agreements.
2) The PR to add LTS is here - https://github.com/zowe/zowe.github.io/pull/932
3) The issue is that Nightly refers to the practice of builds. We release Nightly builds for Maintenance, Active and Under Development. Therefore this type of release isn't linked to the stages of the development.

**Comment by balhar-jakub** [comment] 2024-07-15 08:28
The PR with all the updates is merged. Including https://github.com/zowe/zowe.github.io/pull/932 and as such I am closing the issue as resolved.

**Closed by balhar-jakub** 2024-07-15 08:28 UTC
Labels: onboarding, community-issue
