### ISSUE TITLE
Add Issue Templates Across Zowe Repositories

### ISSUE THREAD

**Issue by MarkAckert** [zowe/community#49] opened 2019-02-21 15:36 UTC
Create a consistent issue submission interface across all Zowe repositories. Some domain-specific information may be included in bug/feature request on a repository-by-repository basis, but the look-and-feel should be consistent.

**Comment by Joe-Winchester** [comment] 2019-02-22 15:22
Is it posible to add this to zowe-install-packaging repo please ?

**Comment by Tbr00ksy** [comment] 2019-04-29 16:19
@MarkAckert I see that this still have the 1.0.3 milestone. Can we close this issue?

**Comment by Joe-Winchester** [comment] 2019-04-30 09:30
@Tbr00ksy - I think this isn't yet finished as not all repos have the same template, for example with zowe-install-packaging when you create a new issue there is no template and you get a blank form

![image](https://user-images.githubusercontent.com/28100302/56952532-6e06ff80-6b32-11e9-9f9c-5b5f0e2577b6.png)

by contrast in for api you get the ability to choose whether the new issue is a bug or feature request

![image](https://user-images.githubusercontent.com/28100302/56952667-bc1c0300-6b32-11e9-9071-5b27669e79c8.png)

which in turn gives you a pre-filled template to follow

![image](https://user-images.githubusercontent.com/28100302/56952699-d229c380-6b32-11e9-800b-7fa1f92fe616.png)



Some repos such as the VS code one also has the guidelines to use at the top of the issues tab to give people more help

![image](https://user-images.githubusercontent.com/28100302/56952603-95f66300-6b32-11e9-84ff-854e71b23bc9.png)

The issue is to track getting consistency across the repositories.

**Comment by balhar-jakub** [comment] 2021-02-16 15:16
Does this issue still remain? And if so should we push on it or close it?

**Comment by balhar-jakub** [comment] 2021-02-23 15:05
Based on the communication on the Architecture this issue remains and will be solved later on.

**Comment by balhar-jakub** [comment] 2024-01-03 15:49
Done for the key repositories for key squads.

**Closed by balhar-jakub** 2024-01-03 15:49 UTC
Labels: enhancement, TSC
