### ISSUE TITLE
Unencoded special characters in request URLs

### ISSUE THREAD

**Issue by weinfurt** [zowe/community#1858] opened 2023-03-01 13:38 UTC
APIML is getting several issues from the Zowe CLI squad related to the presence of special characters in request URLs when submitting JCLs. The last issue is https://github.com/zowe/zowe-cli/issues/1651.

The topic to discuss is the expected behavior from both Zowe CLI and APIML sides. Who should be responsible to encode any special characters in URLs? Should API ML accept unencoded URLs?

Thank you for taking the time to submit a topic for the architecture call.
diff --git a/.github/ISSUE_TEMPLATE/tsc_requests.md b/.github/ISSUE_TEMPLATE/tsc_requests.md

**Comment by weinfurt** [comment] 2023-03-07 09:35
Another issue has been found with special characters in password https://github.com/zowe/zowe-cli/issues/1645

**Comment by balhar-jakub** [comment] 2023-05-06 07:49
Closing the issue as the problem is being handled on the client side.

**Closed by balhar-jakub** 2023-05-06 07:49 UTC
