### ISSUE TITLE
Sensitive terminology in Zowe (TSC) 

### ISSUE THREAD

**Issue by solsu01** [zowe/community#958] opened 2020-06-11 20:01 UTC
With the current climate, it was brought to my attention that it might be prudent to proactively avoid terms like whitelist/blacklist or master/slave in open source projects. Examples: https://github.com/rails/rails/issues/33677 https://www.postgresql.org/message-id/4DC14C0F-2211-48A5-A45E-3671BF97E9D6%40excoventures.com

Here are results from a quick github search for zowe: https://github.com/search?q=org%3Azowe+whitelist+OR+blacklist+OR+slave&type=Code

**Comment by dkelosky** [comment] 2021-01-20 18:54
https://inclusivenaming.org/language/word-list/ has guidance that is a bit different than the guidance listed above.  Do we  guidance that has been agreed upon?

**Comment by balhar-jakub** [comment] 2021-02-11 12:34
Would it be possible to link the issues created in the squad repos to this issue, so that it's simple to see the status?

The API ML squad one is: https://github.com/zowe/api-layer/issues/934

**Comment by jmertic** [comment] 2022-12-13 12:52
Is this still ongoing?

**Comment by balhar-jakub** [comment] 2022-12-14 09:16
According to LFX insights, there is still some sensitive terminology used somewhere. 

I don't think this will ever stop, but do we need to have the issue for it? Probably not.

**Comment by balhar-jakub** [comment] 2023-04-20 12:59
According to the LFX Security we still have some sensitive words used across the place. 

![image.png](https://images.zenhubusercontent.com/5e328700dee80e40ff9ee8f5/b26dad0a-98a1-4837-85b1-3099182fe9ec)

**Comment by balhar-jakub** [comment] 2023-05-04 13:09
The existence of the issue isn't very useful, as such I will close the issue. 

The aim is instead on a yearly basis to go through the LFX Insights and remove newly found issues.

**Closed by balhar-jakub** 2023-05-04 13:09 UTC
Labels: TSC
